language: java
script:
- git clone --branch=master https://github.com/openaire/guidelines-cris-managers.git ../guidelines-cris-managers
- mvn package -Dmaven.javadoc.skip=true -B -V
- java -jar target/openaire-cris-validator-*-jar-with-dependencies.jar file:samples/
